on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: Build
jobs:
  build:
    name: "Package"
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ./build/package.sh ./ ./dist
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: package
          path: dist

  test:
    name: Test
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ./tests/run.sh
