on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build
jobs:
  build:
    name: "Package"
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: ./build/package.sh ./ ./dist
      - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9
        with:
          name: package
          path: dist

  test:
    name: Test
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - run: ./tests/run.sh
