on:
  release:
    types:
      - published

name: Release
jobs:
  release:
    name: "Package"
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - run: ./build/package.sh ./ ./dist
      - uses: SierraSoftworks/gh-releases@fe589e8c033b997e31780791f3cab3246d0726d3
        with:
          files: |
            ./dist/tailscale-unifi.tgz
            ./dist/tailscale-unifi.tgz | tailscale-udm.tgz
          overwrite: "true"
          token: "${{ secrets.GITHUB_TOKEN }}"
