on:
  release:
    types:
      - published

name: Release
jobs:
  release:
    name: "Package"
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - run: ./build/package.sh ./ ./dist
      - uses: SierraSoftworks/gh-releases@5e867a2c72a109b0fb541a089fba34853a8e071e
        with:
          files: |
            ./dist/tailscale-unifi.tgz
            ./dist/tailscale-unifi.tgz | tailscale-udm.tgz
          overwrite: "true"
          token: "${{ secrets.GITHUB_TOKEN }}"
